@startuml

title __RSSCLASSES's Class Diagram__\n

  namespace com.code.group3finalproject {
    namespace RSSClasses {
      class com.code.group3finalproject.RSSClasses.RSSManagedClasses {
          ~ possibleFeeds : ArrayList<RSSNewsFeed>
          + RSSManagedClasses()
          + getAllFeeds()
          + getSelectedFeeds()
          + printFeedNames()
          + toggleInclusion()
      }
    }
  }
  

  namespace com.code.group3finalproject {
    namespace RSSClasses {
      class com.code.group3finalproject.RSSClasses.RSSNewsFeed {
          - RSSFeedURL : String
          - includeFeed : Boolean
          - name : String
          + RSSNewsFeed()
          + getDescriptionTag()
          + getHyperLinkTag()
          + getImageLinkTag()
          + getIncludeFeed()
          + getItemTag()
          + getPublicationDateTag()
          + getRSSFeedName()
          + getRSSFeedURL()
          + getTitleTag()
          + isIncluded()
          + toggleInclusion()
      }
    }
  }
  

  namespace com.code.group3finalproject {
    namespace RSSClasses {
      class com.code.group3finalproject.RSSClasses.RSSNewsObject {
          {static} + CREATOR : Creator<RSSNewsObject>
          - articleURL : String
          - imageURL : String
          - newsDescription : String
          - newsTitle : String
          - publicationDate : String
          + RSSNewsObject()
          + describeContents()
          + getArticleURL()
          + getImageURL()
          + getNewsDescription()
          + getNewsTitle()
          + getPublicationDate()
          + isArticleLinkRequired()
          + isDateRequired()
          + isDescriptionRequired()
          + isImageRequired()
          + isTitleRequired()
          + setArticleURL()
          + setImageURL()
          + setNewsDescription()
          + setNewsTitle()
          + setPublicationDate()
          + writeToParcel()
          # RSSNewsObject()
      }
    }
  }
  

  com.code.group3finalproject.RSSClasses.RSSManagedClasses .up.|> java.io.Serializable
  com.code.group3finalproject.RSSClasses.RSSNewsFeed .up.|> java.io.Serializable
  com.code.group3finalproject.RSSClasses.RSSNewsObject .up.|> android.os.Parcelable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
